[2024-09-29T12:36:07.456+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T12:36:07.472+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-09-29T12:36:07.491+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-09-29T12:36:07.494+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T12:36:07.509+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-09-18 00:00:00+00:00
[2024-09-29T12:36:07.518+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19774) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T12:36:07.521+0000] {standard_task_runner.py:72} INFO - Started process 19782 to run task
[2024-09-29T12:36:07.530+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '854', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpflsx9bgr']
[2024-09-29T12:36:07.534+0000] {standard_task_runner.py:105} INFO - Job 854: Subtask postgres_to_s3
[2024-09-29T12:36:07.574+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-29T12:36:07.682+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-18T00:00:00+00:00 [running]> on host 6851fee35b72
[2024-09-29T12:36:07.683+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-29T12:36:07.785+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v01' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-09-29T12:36:07.786+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T12:36:07.832+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T12:36:07.855+0000] {dag_with_postgres_hooks.py:29} INFO - Saved orders dat in text file get_rders.txt
[2024-09-29T12:36:07.858+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-29T12:36:07.884+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T12:36:07.888+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20240929T123607, end_date=20240929T123607
[2024-09-29T12:36:07.922+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T12:36:07.958+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T12:36:07.966+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T12:41:16.719+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T12:41:16.750+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-09-29T12:41:16.762+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-09-29T12:41:16.763+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T12:41:16.781+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-09-18 00:00:00+00:00
[2024-09-29T12:41:16.799+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=21174) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T12:41:16.801+0000] {standard_task_runner.py:72} INFO - Started process 21179 to run task
[2024-09-29T12:41:16.807+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '883', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpakhvkj1b']
[2024-09-29T12:41:16.813+0000] {standard_task_runner.py:105} INFO - Job 883: Subtask postgres_to_s3
[2024-09-29T12:41:16.841+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-29T12:41:16.975+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-18T00:00:00+00:00 [running]> on host 6851fee35b72
[2024-09-29T12:41:16.981+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-29T12:41:17.127+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v01' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-09-29T12:41:17.130+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T12:41:17.163+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T12:41:17.187+0000] {dag_with_postgres_hooks.py:29} INFO - Saved orders dat in text file get_rders.txt
[2024-09-29T12:41:17.187+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-29T12:41:17.201+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T12:41:17.202+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20240929T124116, end_date=20240929T124117
[2024-09-29T12:41:17.240+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T12:41:17.260+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T12:41:17.261+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
