[2024-09-28T11:54:38.940+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-28T11:54:38.949+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_with_python_v4.get_name manual__2024-09-28T11:54:37.924451+00:00 [queued]>
[2024-09-28T11:54:38.953+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_with_python_v4.get_name manual__2024-09-28T11:54:37.924451+00:00 [queued]>
[2024-09-28T11:54:38.953+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-28T11:54:38.961+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_name> on 2024-09-28 11:54:37.924451+00:00
[2024-09-28T11:54:38.966+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2268) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-28T11:54:38.967+0000] {standard_task_runner.py:72} INFO - Started process 2269 to run task
[2024-09-28T11:54:38.966+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag_with_python_v4', 'get_name', 'manual__2024-09-28T11:54:37.924451+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpnx8zqxuf']
[2024-09-28T11:54:38.968+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask get_name
[2024-09-28T11:54:39.015+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag_with_python_v4.get_name manual__2024-09-28T11:54:37.924451+00:00 [running]> on host f9a59cccd6d1
[2024-09-28T11:54:39.052+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='first_dag_with_python_v4' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-09-28T11:54:37.924451+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-28T11:54:37.924451+00:00'
[2024-09-28T11:54:39.053+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-28T11:54:39.061+0000] {python.py:240} INFO - Done. Returned value was: Jerry
[2024-09-28T11:54:39.071+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-28T11:54:39.071+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag_with_python_v4, task_id=get_name, run_id=manual__2024-09-28T11:54:37.924451+00:00, execution_date=20240928T115437, start_date=20240928T115438, end_date=20240928T115439
[2024-09-28T11:54:39.111+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-28T11:54:39.122+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-28T11:54:39.123+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
