[2024-09-29T03:39:38.701+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:39:38.709+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table manual__2024-09-29T03:39:36.208591+00:00 [queued]>
[2024-09-29T03:39:38.713+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table manual__2024-09-29T03:39:36.208591+00:00 [queued]>
[2024-09-29T03:39:38.713+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:39:38.718+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): delete_from_table> on 2024-09-29 03:39:36.208591+00:00
[2024-09-29T03:39:38.722+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20514) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:39:38.723+0000] {standard_task_runner.py:72} INFO - Started process 20515 to run task
[2024-09-29T03:39:38.722+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'delete_from_table', 'manual__2024-09-29T03:39:36.208591+00:00', '--job-id', '560', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp0oz52q5o']
[2024-09-29T03:39:38.724+0000] {standard_task_runner.py:105} INFO - Job 560: Subtask delete_from_table
[2024-09-29T03:39:38.743+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.delete_from_table manual__2024-09-29T03:39:36.208591+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:39:38.780+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='delete_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T03:39:36.208591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T03:39:36.208591+00:00'
[2024-09-29T03:39:38.780+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:39:38.788+0000] {sql.py:266} INFO - Executing: 
            delete from dag_runs where dt = '2024-09-29' and dag_id='dag_with_postgres_operator_v04'
            
[2024-09-29T03:39:38.793+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:39:38.798+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:39:38.805+0000] {sql.py:509} INFO - Running statement: 
            delete from dag_runs where dt = '2024-09-29' and dag_id='dag_with_postgres_operator_v04'
            , parameters: None
[2024-09-29T03:39:38.810+0000] {sql.py:518} INFO - Rows affected: 1
[2024-09-29T03:39:38.816+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:39:38.817+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=delete_from_table, run_id=manual__2024-09-29T03:39:36.208591+00:00, execution_date=20240929T033936, start_date=20240929T033938, end_date=20240929T033938
[2024-09-29T03:39:38.864+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T03:39:38.874+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:39:38.875+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
