[2024-09-29T03:37:51.475+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:37:51.508+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-09-29T03:37:51.546+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-09-29T03:37:51.548+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:37:51.590+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-18 00:00:00+00:00
[2024-09-29T03:37:51.624+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20276) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:37:51.626+0000] {standard_task_runner.py:72} INFO - Started process 20291 to run task
[2024-09-29T03:37:51.609+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '532', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpjm7abdun']
[2024-09-29T03:37:51.628+0000] {standard_task_runner.py:105} INFO - Job 532: Subtask insert_into_table
[2024-09-29T03:37:51.698+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-18T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:37:51.912+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-09-29T03:37:51.915+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:37:51.950+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-18', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:37:51.965+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:51.980+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:51.993+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-18', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:37:51.997+0000] {sql.py:518} INFO - Rows affected: 1
[2024-09-29T03:37:52.012+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:37:52.013+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20240929T033751, end_date=20240929T033752
[2024-09-29T03:37:52.061+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T03:37:52.088+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
