[2024-09-29T12:36:12.254+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T12:36:12.262+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-29T12:36:12.265+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-29T12:36:12.265+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T12:36:12.270+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-09-24 00:00:00+00:00
[2024-09-29T12:36:12.274+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19805) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T12:36:12.274+0000] {standard_task_runner.py:72} INFO - Started process 19806 to run task
[2024-09-29T12:36:12.274+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2024-09-24T00:00:00+00:00', '--job-id', '860', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmprthqpq6w']
[2024-09-29T12:36:12.275+0000] {standard_task_runner.py:105} INFO - Job 860: Subtask postgres_to_s3
[2024-09-29T12:36:12.282+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-29T12:36:12.297+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-24T00:00:00+00:00 [running]> on host 6851fee35b72
[2024-09-29T12:36:12.298+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-29T12:36:12.360+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v01' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-09-29T12:36:12.361+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T12:36:12.385+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T12:36:12.395+0000] {dag_with_postgres_hooks.py:29} INFO - Saved orders dat in text file get_rders.txt
[2024-09-29T12:36:12.396+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-29T12:36:12.403+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T12:36:12.403+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, run_id=scheduled__2024-09-24T00:00:00+00:00, execution_date=20240924T000000, start_date=20240929T123612, end_date=20240929T123612
[2024-09-29T12:36:12.416+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T12:36:12.426+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T12:36:12.427+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T12:41:20.701+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T12:41:20.738+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-29T12:41:20.758+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-29T12:41:20.760+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T12:41:20.784+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-09-24 00:00:00+00:00
[2024-09-29T12:41:20.802+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=21231) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T12:41:20.806+0000] {standard_task_runner.py:72} INFO - Started process 21241 to run task
[2024-09-29T12:41:20.803+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2024-09-24T00:00:00+00:00', '--job-id', '889', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpvy_rnrhh']
[2024-09-29T12:41:20.811+0000] {standard_task_runner.py:105} INFO - Job 889: Subtask postgres_to_s3
[2024-09-29T12:41:20.843+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-29T12:41:20.913+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2024-09-24T00:00:00+00:00 [running]> on host 6851fee35b72
[2024-09-29T12:41:20.918+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-29T12:41:21.040+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v01' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-09-29T12:41:21.042+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T12:41:21.068+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T12:41:21.086+0000] {dag_with_postgres_hooks.py:29} INFO - Saved orders dat in text file get_rders.txt
[2024-09-29T12:41:21.093+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-29T12:41:21.106+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T12:41:21.108+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, run_id=scheduled__2024-09-24T00:00:00+00:00, execution_date=20240924T000000, start_date=20240929T124120, end_date=20240929T124121
[2024-09-29T12:41:21.161+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T12:41:21.171+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T12:41:21.172+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
